version: 2.1

orbs:
  docker: circleci/docker@2.2

workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: devkteam/sonarqube-report
          tag: latest
          update-description: true
          docker-username: DOCKERHUB_USER
          docker-password: DOCKERHUB_PASS
          context: kanopi-code
          filters:
            branches:
              only: main
      - docker/publish:
          image: devkteam/sonarqube-report
          tag: 'build-${CIRCLE_SHA1:0:7}'
          docker-username: DOCKERHUB_USER
          docker-password: DOCKERHUB_PASS
          update-description: false
          context: kanopi-code
          filters:
            branches:
              ignore: main
